### ISSUE TITLE
Options used with autohint

### ISSUE THREAD

**Issue by khaledhosny** [adobe-fonts/source-serif-pro#25]
I’m trying to use the fonts for testing changes to `autohint`, but when I run `autohint` from AFDKO master with `--all` option only I get changes to in some glyphs, so I’m wondering whether I need to pass specific option to reproduce the existing hinting or the changes are due to different versions of the autohinter used.

**Comment by miguelsousa** [comment]
I've just pushed a recent fix that may have something to do with what you're experiencing. Please give it a try and let me know.

**Comment by khaledhosny** [comment]
Still seeing the same differences on master, but if I switch to 2.5.65322 tag the differences go away, so looks like an AFDKO change after all. Will try bisecting it.

**Comment by khaledhosny** [comment]
Bisecting shows that the difference is caused by [this AFDKO commit](https://github.com/adobe-type-tools/afdko/commit/2c3cbf35b05557179e72d36f6fc28eabcd1427c5), the commit message suggests that the old output is the broken one.
